export default {
  port: process.env.PORT || 3000,
  env: process.env.NODE_ENV || "development",
  dbUri: process.env.dbUri,
  jwtSecret: process.env.JWT_SECRET,
  sessionSecret: process.env.SESSION_SECRET,
  googleClientId: process.env.GOOGLE_CLIENT_ID,
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
  callbackURL: process.env.CALLBACK_URL,
  cloudinaryCloudName: process.env.CLOUDINARY_CLOUD_NAME,
  cloudinaryApiKey: process.env.CLOUDINARY_API_KEY,
  cloudinaryApiSecret: process.env.CLOUDINARY_API_SECRET,
  emailHostName: process.env.EMAIL_HOST,
  emailHostPort: process.env.EMAIL_HOST_PORT,
  emailFrom: process.env.EMAIL_FROM,
  sendgridApiKey: process.env.SENDGRID_API_KEY,
  jwtExpiresIn: process.env.jwtExpiresIn,
  jwtRefreshExpiresIn: process.env.jwtRefreshExpiresIn,
  jwtRefreshExpirationInterval: process.env.jwtRefreshExpirationInterval,
  logLevel: process.env.logLevel,
};
